#!/usr/bin/env python3
"""
Regenerate sim/slip39_vectors.h from the official SLIP-0039 test vectors.

The generated header is committed so the suite runs offline and so a vector
never changes silently under us. Re-run this only to pick up an upstream
addition, and read the diff.

  python3 sim/gen_slip39_vectors.py vectors.json > sim/slip39_vectors.h

Source: https://github.com/trezor/python-shamir-mnemonic/blob/master/vectors.json
Format: [description, [mnemonics...], master_secret_hex_or_empty, xprv]
An empty master secret means the set MUST be rejected.
"""

import json
import sys


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    vectors = json.load(open(sys.argv[1]))
    out = sys.stdout
    out.write("/* Generated by sim/gen_slip39_vectors.py -- do not edit. */\n")
    out.write("/* Official SLIP-0039 test vectors, passphrase \"TREZOR\". */\n")
    out.write("#ifndef SLIP39_VECTORS_H\n#define SLIP39_VECTORS_H\n\n")
    out.write("typedef struct {\n"
              "    const char *description;\n"
              "    const char *const *mnemonics;\n"
              "    int mnemonic_count;\n"
              "    const char *secret_hex; /* empty => must be rejected */\n"
              "} slip39_vector;\n\n")

    for i, (desc, mnemonics, secret, _xprv) in enumerate(vectors):
        out.write("static const char *const vec_%d[] = {\n" % i)
        for m in mnemonics:
            out.write("    %s,\n" % c_str(m))
        out.write("};\n")

    out.write("\nstatic const slip39_vector SLIP39_VECTORS[] = {\n")
    for i, (desc, mnemonics, secret, _xprv) in enumerate(vectors):
        out.write("    { %s, vec_%d, %d, %s },\n"
                  % (c_str(desc), i, len(mnemonics), c_str(secret)))
    out.write("};\n\n#define SLIP39_VECTOR_COUNT "
              "(int)(sizeof(SLIP39_VECTORS) / sizeof(SLIP39_VECTORS[0]))\n")
    out.write("\n#endif /* SLIP39_VECTORS_H */\n")


main()
