/* Generated by sim/gen_slip39_vectors.py -- do not edit. */
/* Official SLIP-0039 test vectors, passphrase "TREZOR". */
#ifndef SLIP39_VECTORS_H
#define SLIP39_VECTORS_H

typedef struct {
    const char *description;
    const char *const *mnemonics;
    int mnemonic_count;
    const char *secret_hex; /* empty => must be rejected */
} slip39_vector;

static const char *const vec_0[] = {
    "duckling enlarge academic academic agency result length solution fridge kidney coal piece deal husband erode duke ajar critical decision keyboard",
};
static const char *const vec_1[] = {
    "duckling enlarge academic academic agency result length solution fridge kidney coal piece deal husband erode duke ajar critical decision kidney",
};
static const char *const vec_2[] = {
    "duckling enlarge academic academic email result length solution fridge kidney coal piece deal husband erode duke ajar music cargo fitness",
};
static const char *const vec_3[] = {
    "shadow pistol academic always adequate wildlife fancy gross oasis cylinder mustang wrist rescue view short owner flip making coding armed",
    "shadow pistol academic acid actress prayer class unknown daughter sweater depict flip twice unkind craft early superior advocate guest smoking",
};
static const char *const vec_4[] = {
    "shadow pistol academic always adequate wildlife fancy gross oasis cylinder mustang wrist rescue view short owner flip making coding armed",
};
static const char *const vec_5[] = {
    "adequate smoking academic acid debut wine petition glen cluster slow rhyme slow simple epidemic rumor junk tracks treat olympic tolerate",
    "adequate stay academic agency agency formal party ting frequent learn upstairs remember smear leaf damage anatomy ladle market hush corner",
};
static const char *const vec_6[] = {
    "peasant leaves academic acid desert exact olympic math alive axle trial tackle drug deny decent smear dominant desert bucket remind",
    "peasant leader academic agency cultural blessing percent network envelope medal junk primary human pumps jacket fragment payroll ticket evoke voice",
};
static const char *const vec_7[] = {
    "liberty category beard echo animal fawn temple briefing math username various wolf aviation fancy visual holy thunder yelp helpful payment",
    "liberty category beard email beyond should fancy romp founder easel pink holy hairy romp loyalty material victim owner toxic custody",
    "liberty category academic easy being hazard crush diminish oral lizard reaction cluster force dilemma deploy force club veteran expect photo",
};
static const char *const vec_8[] = {
    "average senior academic leaf broken teacher expect surface hour capture obesity desire negative dynamic dominant pistol mineral mailman iris aide",
    "average senior academic agency curious pants blimp spew clothes slice script dress wrap firm shaft regular slavery negative theater roster",
};
static const char *const vec_9[] = {
    "music husband acrobat acid artist finance center either graduate swimming object bike medical clothes station aspect spider maiden bulb welcome",
    "music husband acrobat agency advance hunting bike corner density careful material civil evil tactics remind hawk discuss hobo voice rainbow",
    "music husband beard academic black tricycle clock mayor estimate level photo episode exclude ecology papa source amazing salt verify divorce",
};
static const char *const vec_10[] = {
    "device stay academic always dive coal antenna adult black exceed stadium herald advance soldier busy dryer daughter evaluate minister laser",
    "device stay academic always dwarf afraid robin gravity crunch adjust soul branch walnut coastal dream costume scholar mortgage mountain pumps",
};
static const char *const vec_11[] = {
    "hour painting academic academic device formal evoke guitar random modern justice filter withdraw trouble identify mailman insect general cover oven",
    "hour painting academic agency artist again daisy capital beaver fiber much enjoy suitable symbolic identify photo editor romp float echo",
};
static const char *const vec_12[] = {
    "guilt walnut academic acid deliver remove equip listen vampire tactics nylon rhythm failure husband fatigue alive blind enemy teaspoon rebound",
    "guilt walnut academic agency brave hamster hobo declare herd taste alpha slim criminal mild arcade formal romp branch pink ambition",
};
static const char *const vec_13[] = {
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange unusual garlic promise voice",
};
static const char *const vec_14[] = {
    "eraser senior decision scared cargo theory device idea deliver modify curly include pancake both news skin realize vitamins away join",
    "eraser senior decision roster beard treat identify grumpy salt index fake aviation theater cubic bike cause research dragon emphasis counter",
};
static const char *const vec_15[] = {
    "eraser senior decision shadow artist work morning estate greatest pipeline plan ting petition forget hormone flexible general goat admit surface",
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange unusual garlic promise voice",
};
static const char *const vec_16[] = {
    "eraser senior decision roster beard treat identify grumpy salt index fake aviation theater cubic bike cause research dragon emphasis counter",
    "eraser senior ceramic snake clay various huge numb argue hesitate auction category timber browser greatest hanger petition script leaf pickup",
    "eraser senior ceramic shaft dynamic become junior wrist silver peasant force math alto coal amazing segment yelp velvet image paces",
    "eraser senior ceramic round column hawk trust auction smug shame alive greatest sheriff living perfect corner chest sled fumes adequate",
    "eraser senior decision smug corner ruin rescue cubic angel tackle skin skunk program roster trash rumor slush angel flea amazing",
};
static const char *const vec_17[] = {
    "eraser senior decision smug corner ruin rescue cubic angel tackle skin skunk program roster trash rumor slush angel flea amazing",
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange unusual garlic promise voice",
    "eraser senior decision scared cargo theory device idea deliver modify curly include pancake both news skin realize vitamins away join",
};
static const char *const vec_18[] = {
    "eraser senior beard romp adorn nuclear spill corner cradle style ancient family general leader ambition exchange unusual garlic promise voice",
    "eraser senior acrobat romp bishop medical gesture pumps secret alive ultimate quarter priest subject class dictate spew material endless market",
};
static const char *const vec_19[] = {
    "theory painting academic academic armed sweater year military elder discuss acne wildlife boring employer fused large satoshi bundle carbon diagnose anatomy hamster leaves tracks paces beyond phantom capital marvel lips brave detect luck",
};
static const char *const vec_20[] = {
    "theory painting academic academic armed sweater year military elder discuss acne wildlife boring employer fused large satoshi bundle carbon diagnose anatomy hamster leaves tracks paces beyond phantom capital marvel lips brave detect lunar",
};
static const char *const vec_21[] = {
    "theory painting academic academic campus sweater year military elder discuss acne wildlife boring employer fused large satoshi bundle carbon diagnose anatomy hamster leaves tracks paces beyond phantom capital marvel lips facility obtain sister",
};
static const char *const vec_22[] = {
    "humidity disease academic always aluminum jewelry energy woman receiver strategy amuse duckling lying evidence network walnut tactics forget hairy rebound impulse brother survive clothes stadium mailman rival ocean reward venture always armed unwrap",
    "humidity disease academic agency actress jacket gross physics cylinder solution fake mortgage benefit public busy prepare sharp friar change work slow purchase ruler again tricycle involve viral wireless mixture anatomy desert cargo upgrade",
};
static const char *const vec_23[] = {
    "humidity disease academic always aluminum jewelry energy woman receiver strategy amuse duckling lying evidence network walnut tactics forget hairy rebound impulse brother survive clothes stadium mailman rival ocean reward venture always armed unwrap",
};
static const char *const vec_24[] = {
    "smear husband academic acid deadline scene venture distance dive overall parking bracelet elevator justice echo burning oven chest duke nylon",
    "smear isolate academic agency alpha mandate decorate burden recover guard exercise fatal force syndrome fumes thank guest drift dramatic mule",
};
static const char *const vec_25[] = {
    "finger trash academic acid average priority dish revenue academic hospital spirit western ocean fact calcium syndrome greatest plan losing dictate",
    "finger traffic academic agency building lilac deny paces subject threaten diploma eclipse window unknown health slim piece dragon focus smirk",
};
static const char *const vec_26[] = {
    "flavor pink beard echo depart forbid retreat become frost helpful juice unwrap reunion credit math burning spine black capital lair",
    "flavor pink beard email diet teaspoon freshman identify document rebound cricket prune headset loyalty smell emission skin often square rebound",
    "flavor pink academic easy credit cage raisin crazy closet lobe mobile become drink human tactics valuable hand capture sympathy finger",
};
static const char *const vec_27[] = {
    "column flea academic leaf debut extra surface slow timber husky lawsuit game behavior husky swimming already paper episode tricycle scroll",
    "column flea academic agency blessing garbage party software stadium verify silent umbrella therapy decorate chemical erode dramatic eclipse replace apart",
};
static const char *const vec_28[] = {
    "smirk pink acrobat acid auction wireless impulse spine sprinkle fortune clogs elbow guest hush loyalty crush dictate tracks airport talent",
    "smirk pink acrobat agency dwarf emperor ajar organize legs slice harvest plastic dynamic style mobile float bulb health coding credit",
    "smirk pink beard academic alto strategy carve shame language rapids ruin smart location spray training acquire eraser endorse submit peaceful",
};
static const char *const vec_29[] = {
    "fishing recover academic always device craft trend snapshot gums skin downtown watch device sniff hour clock public maximum garlic born",
    "fishing recover academic always aircraft view software cradle fangs amazing package plastic evaluate intend penalty epidemic anatomy quarter cage apart",
};
static const char *const vec_30[] = {
    "evoke garden academic academic answer wolf scandal modern warmth station devote emerald market physics surface formal amazing aquatic gesture medical",
    "evoke garden academic agency deal revenue knit reunion decrease magazine flexible company goat repair alarm military facility clogs aide mandate",
};
static const char *const vec_31[] = {
    "river deal academic acid average forbid pistol peanut custody bike class aunt hairy merit valid flexible learn ajar very easel",
    "river deal academic agency camera amuse lungs numb isolate display smear piece traffic worthy year patrol crush fact fancy emission",
};
static const char *const vec_32[] = {
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough stadium",
};
static const char *const vec_33[] = {
    "wildlife deal decision scared acne fatal snake paces obtain election dryer dominant romp tactics railroad marvel trust helpful flip peanut theory theater photo luck install entrance taxi step oven network dictate intimate listen",
    "wildlife deal decision smug ancestor genuine move huge cubic strategy smell game costume extend swimming false desire fake traffic vegan senior twice timber submit leader payroll fraction apart exact forward pulse tidy install",
};
static const char *const vec_34[] = {
    "wildlife deal decision shadow analysis adjust bulb skunk muscle mandate obesity total guitar coal gravity carve slim jacket ruin rebuild ancestor numerous hour mortgage require herd maiden public ceiling pecan pickup shadow club",
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough stadium",
};
static const char *const vec_35[] = {
    "wildlife deal ceramic round aluminum pitch goat racism employer miracle percent math decision episode dramatic editor lily prospect program scene rebuild display sympathy have single mustang junction relate often chemical society wits estate",
    "wildlife deal decision scared acne fatal snake paces obtain election dryer dominant romp tactics railroad marvel trust helpful flip peanut theory theater photo luck install entrance taxi step oven network dictate intimate listen",
    "wildlife deal ceramic scatter argue equip vampire together ruin reject literary rival distance aquatic agency teammate rebound false argue miracle stay again blessing peaceful unknown cover beard acid island language debris industry idle",
    "wildlife deal ceramic snake agree voter main lecture axis kitchen physics arcade velvet spine idea scroll promise platform firm sharp patrol divorce ancestor fantasy forbid goat ajar believe swimming cowboy symbolic plastic spelling",
    "wildlife deal decision shadow analysis adjust bulb skunk muscle mandate obesity total guitar coal gravity carve slim jacket ruin rebuild ancestor numerous hour mortgage require herd maiden public ceiling pecan pickup shadow club",
};
static const char *const vec_36[] = {
    "wildlife deal decision scared acne fatal snake paces obtain election dryer dominant romp tactics railroad marvel trust helpful flip peanut theory theater photo luck install entrance taxi step oven network dictate intimate listen",
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough stadium",
    "wildlife deal decision smug ancestor genuine move huge cubic strategy smell game costume extend swimming false desire fake traffic vegan senior twice timber submit leader payroll fraction apart exact forward pulse tidy install",
};
static const char *const vec_37[] = {
    "wildlife deal beard romp alcohol space mild usual clothes union nuclear testify course research heat listen task location thank hospital slice smell failure fawn helpful priest ambition average recover lecture process dough stadium",
    "wildlife deal acrobat romp anxiety axis starting require metric flexible geology game drove editor edge screw helpful have huge holy making pitch unknown carve holiday numb glasses survive already tenant adapt goat fangs",
};
static const char *const vec_38[] = {
    "junk necklace academic academic acne isolate join hesitate lunar roster dough calcium chemical ladybug amount mobile glasses verify cylinder",
};
static const char *const vec_39[] = {
    "fraction necklace academic academic award teammate mouse regular testify coding building member verdict purchase blind camera duration email prepare spirit quarter",
};
static const char *const vec_40[] = {
    "herald flea academic cage avoid space trend estate dryer hairy evoke eyebrow improve airline artwork garlic premium duration prevent oven",
    "herald flea academic client blue skunk class goat luxury deny presence impulse graduate clay join blanket bulge survive dish necklace",
    "herald flea academic acne advance fused brother frozen broken game ranked ajar already believe check install theory angry exercise adult",
};
static const char *const vec_41[] = {
    "testify swimming academic academic column loyalty smear include exotic bedroom exotic wrist lobe cover grief golden smart junior estimate learn",
};
static const char *const vec_42[] = {
    "enemy favorite academic acid cowboy phrase havoc level response walnut budget painting inside trash adjust froth kitchen learn tidy punish",
    "enemy favorite academic always academic sniff script carpet romp kind promise scatter center unfair training emphasis evening belong fake enforce",
};
static const char *const vec_43[] = {
    "impulse calcium academic academic alcohol sugar lyrics pajamas column facility finance tension extend space birthday rainbow swimming purple syndrome facility trial warn duration snapshot shadow hormone rhyme public spine counter easy hawk album",
};
static const char *const vec_44[] = {
    "western apart academic always artist resident briefing sugar woman oven coding club ajar merit pecan answer prisoner artist fraction amount desktop mild false necklace muscle photo wealthy alpha category unwrap spew losing making",
    "western apart academic acid answer ancient auction flip image penalty oasis beaver multiple thunder problem switch alive heat inherit superior teaspoon explain blanket pencil numb lend punish endless aunt garlic humidity kidney observe",
};

static const slip39_vector SLIP39_VECTORS[] = {
    { "1. Valid mnemonic without sharing (128 bits)", vec_0, 1, "bb54aac4b89dc868ba37d9cc21b2cece" },
    { "2. Mnemonic with invalid checksum (128 bits)", vec_1, 1, "" },
    { "3. Mnemonic with invalid padding (128 bits)", vec_2, 1, "" },
    { "4. Basic sharing 2-of-3 (128 bits)", vec_3, 2, "b43ceb7e57a0ea8766221624d01b0864" },
    { "5. Basic sharing 2-of-3 (128 bits)", vec_4, 1, "" },
    { "6. Mnemonics with different identifiers (128 bits)", vec_5, 2, "" },
    { "7. Mnemonics with different iteration exponents (128 bits)", vec_6, 2, "" },
    { "8. Mnemonics with mismatching group thresholds (128 bits)", vec_7, 3, "" },
    { "9. Mnemonics with mismatching group counts (128 bits)", vec_8, 2, "" },
    { "10. Mnemonics with greater group threshold than group counts (128 bits)", vec_9, 3, "" },
    { "11. Mnemonics with duplicate member indices (128 bits)", vec_10, 2, "" },
    { "12. Mnemonics with mismatching member thresholds (128 bits)", vec_11, 2, "" },
    { "13. Mnemonics giving an invalid digest (128 bits)", vec_12, 2, "" },
    { "14. Insufficient number of groups (128 bits, case 1)", vec_13, 1, "" },
    { "15. Insufficient number of groups (128 bits, case 2)", vec_14, 2, "" },
    { "16. Threshold number of groups, but insufficient number of members in one group (128 bits)", vec_15, 2, "" },
    { "17. Threshold number of groups and members in each group (128 bits, case 1)", vec_16, 5, "7c3397a292a5941682d7a4ae2d898d11" },
    { "18. Threshold number of groups and members in each group (128 bits, case 2)", vec_17, 3, "7c3397a292a5941682d7a4ae2d898d11" },
    { "19. Threshold number of groups and members in each group (128 bits, case 3)", vec_18, 2, "7c3397a292a5941682d7a4ae2d898d11" },
    { "20. Valid mnemonic without sharing (256 bits)", vec_19, 1, "989baf9dcaad5b10ca33dfd8cc75e42477025dce88ae83e75a230086a0e00e92" },
    { "21. Mnemonic with invalid checksum (256 bits)", vec_20, 1, "" },
    { "22. Mnemonic with invalid padding (256 bits)", vec_21, 1, "" },
    { "23. Basic sharing 2-of-3 (256 bits)", vec_22, 2, "c938b319067687e990e05e0da0ecce1278f75ff58d9853f19dcaeed5de104aae" },
    { "24. Basic sharing 2-of-3 (256 bits)", vec_23, 1, "" },
    { "25. Mnemonics with different identifiers (256 bits)", vec_24, 2, "" },
    { "26. Mnemonics with different iteration exponents (256 bits)", vec_25, 2, "" },
    { "27. Mnemonics with mismatching group thresholds (256 bits)", vec_26, 3, "" },
    { "28. Mnemonics with mismatching group counts (256 bits)", vec_27, 2, "" },
    { "29. Mnemonics with greater group threshold than group counts (256 bits)", vec_28, 3, "" },
    { "30. Mnemonics with duplicate member indices (256 bits)", vec_29, 2, "" },
    { "31. Mnemonics with mismatching member thresholds (256 bits)", vec_30, 2, "" },
    { "32. Mnemonics giving an invalid digest (256 bits)", vec_31, 2, "" },
    { "33. Insufficient number of groups (256 bits, case 1)", vec_32, 1, "" },
    { "34. Insufficient number of groups (256 bits, case 2)", vec_33, 2, "" },
    { "35. Threshold number of groups, but insufficient number of members in one group (256 bits)", vec_34, 2, "" },
    { "36. Threshold number of groups and members in each group (256 bits, case 1)", vec_35, 5, "5385577c8cfc6c1a8aa0f7f10ecde0a3318493262591e78b8c14c6686167123b" },
    { "37. Threshold number of groups and members in each group (256 bits, case 2)", vec_36, 3, "5385577c8cfc6c1a8aa0f7f10ecde0a3318493262591e78b8c14c6686167123b" },
    { "38. Threshold number of groups and members in each group (256 bits, case 3)", vec_37, 2, "5385577c8cfc6c1a8aa0f7f10ecde0a3318493262591e78b8c14c6686167123b" },
    { "39. Mnemonic with insufficient length", vec_38, 1, "" },
    { "40. Mnemonic with invalid master secret length", vec_39, 1, "" },
    { "41. Valid mnemonics which can detect some errors in modular arithmetic", vec_40, 3, "ad6f2ad8b59bbbaa01369b9006208d9a" },
    { "42. Valid extendable mnemonic without sharing (128 bits)", vec_41, 1, "1679b4516e0ee5954351d288a838f45e" },
    { "43. Extendable basic sharing 2-of-3 (128 bits)", vec_42, 2, "48b1a4b80b8c209ad42c33672bdaa428" },
    { "44. Valid extendable mnemonic without sharing (256 bits)", vec_43, 1, "8340611602fe91af634a5f4608377b5235fa2d757c51d720c0c7656249a3035f" },
    { "45. Extendable basic sharing 2-of-3 (256 bits)", vec_44, 2, "8dc652d6d6cd370d8c963141f6d79ba440300f25c467302c1d966bff8f62300d" },
};

#define SLIP39_VECTOR_COUNT (int)(sizeof(SLIP39_VECTORS) / sizeof(SLIP39_VECTORS[0]))

#endif /* SLIP39_VECTORS_H */
