//! LeekWallet companion — Tauri backend.
//!
//! Owns exactly one thing: moving bytes between the frontend and the device.
//! No protocol parsing, no key handling, no policy. The codec lives in
//! `packages/core` where it can be tested under plain Node, and the device
//! decides everything that matters. Keeping this layer dumb is what makes the
//! shell replaceable and keeps the audit surface small.
//!
//! This lives in a library rather than in `main.rs` because Android has no
//! `main()`: the APK loads a shared object and the JVM calls the entry point
//! generated by `tauri::mobile_entry_point`. Desktop's `main.rs` calls the same
//! `run()`, so both platforms boot identical code.

// Serial is a desktop-only transport: Android has no ports to enumerate and
// exposes USB devices through a Java permission API instead. Compiling it for
// Android would fail on serialport's platform code, so the whole surface —
// dependency, state, and commands — is absent there rather than stubbed.
// Stubs would let the frontend believe a transport exists and report a
// connection it does not have.
#[cfg(not(target_os = "android"))]
mod serial;

/// Start the app.
///
/// `mobile_entry_point` is what the generated Android project calls; on desktop
/// the attribute expands to nothing and `main.rs` calls this directly.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default();

    #[cfg(not(target_os = "android"))]
    let builder = builder.manage(serial::Connection::default()).invoke_handler(
        tauri::generate_handler![
            serial::ports,
            serial::connect,
            serial::disconnect,
            serial::request
        ],
    );

    builder
        .run(tauri::generate_context!())
        .expect("failed to start the LeekWallet companion");
}
