//! LeekWallet companion — Tauri backend.
//!
//! Owns exactly one thing: moving bytes between the frontend and the device.
//! No protocol parsing, no key handling, no policy. The codec lives in
//! `packages/core` where it can be tested under plain Node, and the device
//! decides everything that matters. Keeping this layer dumb is what makes the
//! shell replaceable and keeps the audit surface small.
//!
//! This lives in a library rather than in `main.rs` because Android has no
//! `main()`: the APK loads a shared object and the JVM calls the entry point
//! generated by `tauri::mobile_entry_point`. Desktop's `main.rs` calls the same
//! `run()`, so both platforms boot identical code.

// Both transports are present on every platform since T59.
//
// Each transport crate carries two backends behind one API and picks between
// them at build time: `leek-transport-serial` is the `serialport` crate on
// desktop and `tauri-plugin-serialplugin`'s USB Host driver on Android;
// `leek-transport-ble` is btleplug on desktop and `tauri-plugin-blec` on
// Android. Both modules below are therefore the same code on both platforms,
// and so are the commands they export. See each crate's `android.rs` for why
// the phone needs a different way in rather than a different transport.
mod ble;
mod serial;

// The one thing in this backend that is not "move bytes to the device": an
// outbound JSON-RPC call, made here rather than in the webview because the CSP
// governs the webview and not this process. It is what a user-supplied RPC
// endpoint needs to be reachable at all — no build-time allowlist can contain
// an origin the user types in tomorrow. The module is the gatekeeper the
// allowlist used to be; see its header and docs/RPC-ACCESS.md.
//
// Part of that policy — the redirect rule, the response checks, the origin the
// UI displays — is reached only from the HTTP client, which is behind the
// `rpc-proxy` feature (see the module header for why it has to be). It is
// still compiled and still tested without the feature, so the allow only
// silences "you have not called this yet", not a real absence.
#[cfg_attr(not(feature = "rpc-proxy"), allow(dead_code))]
mod rpc;

/// Which transports this build actually has behind it.
///
/// A real capability query, replacing the frontend's old habit of sniffing the
/// user agent for "Android". The frontend must not decide from the presence of
/// an `invoke` bridge that a device is reachable: on Android the bridge exists
/// whether or not anything is wired behind it, and a status badge reading
/// "hardware" on a phone connected to nothing is the one lie a wallet UI must
/// never tell.
#[tauri::command]
fn transports() -> Vec<&'static str> {
    // Identical on both platforms now, and deliberately not written as a
    // platform-conditional constant: the honest claim is "both command sets
    // are compiled and their drivers ship in this binary", and after T59 that
    // is true of the phone as well.
    //
    // Claiming "usb" here is a claim that `ports`/`connect`/`request` will
    // work, so on Android it rests on the Kotlin inside
    // `tauri-plugin-serialplugin` being linked into the APK by Tauri's own
    // project generation — not on the Rust happening to compile. An empty port
    // list or a refused permission are runtime answers with their own
    // messages, not reasons to deny the capability; never advertising a
    // transport that fails at first use is the rule, and a transport that
    // needs the user to approve a dialog has not failed.
    vec!["usb", "ble"]
}

/// Start the app.
///
/// `mobile_entry_point` is what the generated Android project calls; on desktop
/// the attribute expands to nothing and `main.rs` calls this directly.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .manage(ble::Connection::default())
        .manage(serial::Connection::default());

    // Registering the plugins is what installs the Android plugin handles the
    // backends call through; without them every call panics with "plugin
    // handle not initialized". Deliberately absent on desktop, where our own
    // btleplug and `serialport` code talks to the hardware directly and a
    // second stack in the process would only be one more thing to go wrong.
    //
    // Nothing is added to `capabilities/default.json` for either: the plugins'
    // own JS commands are never invoked from the webview, only from Rust, so
    // the window is granted no new surface and the CSP is untouched.
    #[cfg(target_os = "android")]
    let builder = builder
        .plugin(tauri_plugin_blec::init())
        .plugin(tauri_plugin_serialplugin::init());

    builder
        .invoke_handler(tauri::generate_handler![
            transports,
            serial::ports,
            serial::connect,
            serial::disconnect,
            serial::request,
            ble::ble_scan,
            ble::ble_connect,
            ble::ble_disconnect,
            ble::ble_request,
            rpc::rpc_proxy_available,
            rpc::rpc_call
        ])
        .run(tauri::generate_context!())
        .expect("failed to start the LeekWallet companion");
}
