#!/usr/bin/env bash
#
# Re-apply the USB host edits to the generated Android project.
#
# `app/src-tauri/gen/` is generated by `tauri android init` and is gitignored,
# so anything hand-edited there is lost every time it is regenerated. The camera
# permission already taught this lesson once (see check-android-manifest.sh);
# USB is the second instance, and it fails the same way — silently.
#
# Two things are missing from the generated project:
#
#   1. `<uses-feature android:name="android.hardware.usb.host" />`. Without it
#      Android does not treat the app as a USB host client, and UsbManager can
#      return an empty device list on hardware that gates host mode on the
#      declared feature. BLE keeps working, which is what makes this look like
#      "USB is broken" rather than "a manifest line is missing".
#
#   2. `res/xml/device_filter.xml`. The manifest's USB_DEVICE_ATTACHED intent
#      filter references `@xml/device_filter`, and Tauri does not generate it.
#      A dangling resource reference means the attach intent cannot fire, so a
#      board can be plugged in, enumerate at the OS level, and never reach the
#      app.
#
# Run after every `tauri android init`, before building. Idempotent.
set -uo pipefail
cd "$(dirname "$0")/.."

GEN="app/src-tauri/gen/android/app/src/main"
MANIFEST="${GEN}/AndroidManifest.xml"
FILTER="${GEN}/res/xml/device_filter.xml"

if [[ ! -f "${MANIFEST}" ]]; then
    echo "android-usb-host: ${MANIFEST} not found." >&2
    echo "Run 'pnpm --dir app tauri android init' first — gen/ is generated." >&2
    exit 2
fi

if grep -q 'android.hardware.usb.host' "${MANIFEST}"; then
    echo "   uses-feature usb.host already present"
else
    # Anchored on the INTERNET permission, which Tauri always generates.
    python3 - "$MANIFEST" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); s = p.read_text()
a = '<uses-permission android:name="android.permission.INTERNET" />'
if a not in s:
    sys.exit("android-usb-host: no INTERNET permission to anchor on")
p.write_text(s.replace(a, a + '''

    <!-- Applied by scripts/android-usb-host.sh, not generated. required=false
         so the app still installs where there is no OTG support and BLE is the
         only transport. -->
    <uses-feature android:name="android.hardware.usb.host" android:required="false" />''', 1))
PY
    echo "   added uses-feature android.hardware.usb.host"
fi

mkdir -p "$(dirname "${FILTER}")"
cat > "${FILTER}" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!--
  Applied by scripts/android-usb-host.sh. Do not hand-edit; regeneration wipes
  this directory.

  Ids are DECIMAL. Android's parser does not accept 0x-prefixed hex and a hex
  value matches nothing rather than failing, so the hex lives in comments only.

  Espressif covers both boards: the Pixie's ESP32-C3 and the ESP32-S3 both
  speak native USB-Serial-JTAG and enumerate as 303a:1001. Listed by vendor
  without a product id, so a future Espressif part is not excluded by an id
  nobody thought to add. The three bridges are here because a devkit without
  native USB puts one between the chip and the cable, and from Android's side
  the bridge is the device.
-->
<resources>
    <usb-device vendor-id="12346" /> <!-- Espressif 0x303a -->
    <usb-device vendor-id="6790" />  <!-- QinHeng CH340/CH343 0x1a86 -->
    <usb-device vendor-id="4292" />  <!-- Silicon Labs CP210x 0x10c4 -->
    <usb-device vendor-id="1027" />  <!-- FTDI 0x0403 -->
</resources>
XML
echo "   wrote ${FILTER}"
echo "android-usb-host: done. Rebuild the APK for this to take effect."
