#!/usr/bin/env bash
#
# Wire the release keystore into the generated Android project, and refuse to
# be clever about it.
#
# `app/src-tauri/gen/android` is generated by `tauri android init` and is not
# tracked (see app/ANDROID.md, and scripts/check-android-manifest.sh for the
# one thing that regeneration silently loses). Release signing is configured in
# that generated tree, which means it has to be re-applied after every init -
# so it is a script rather than a step in a document that a person performs
# from memory at tag time.
#
# What it does:
#
#   - writes gen/android/keystore.properties from four environment variables,
#     naming a keystore file that already exists somewhere outside the
#     repository. It never creates a keystore, never prints one, and never
#     writes key material anywhere but that one file.
#   - adds a `release` signingConfig to app/build.gradle.kts that reads those
#     properties, but only if the generated file does not already have one.
#     Tauri's template has carried that block in some versions and not others,
#     and two definitions of where the signing config comes from is exactly the
#     kind of thing that ends with an unsigned APK that looks fine.
#
# What it deliberately does not do: decide whether the result is actually
# signed. That is `apksigner verify` on the finished APK, run by the caller -
# an assertion about the artefact beats an assertion about the build files.
#
#   ANDROID_KEYSTORE_PATH=/abs/path/release.keystore \
#   ANDROID_KEYSTORE_PASSWORD=... ANDROID_KEY_ALIAS=... ANDROID_KEY_PASSWORD=... \
#   ./scripts/android-release-signing.sh

set -uo pipefail
cd "$(dirname "$0")/.."

GEN="app/src-tauri/gen/android"
GRADLE="${GEN}/app/build.gradle.kts"

for v in ANDROID_KEYSTORE_PATH ANDROID_KEYSTORE_PASSWORD ANDROID_KEY_ALIAS ANDROID_KEY_PASSWORD; do
    if [[ -z "${!v:-}" ]]; then
        # Named, not dumped: the point is to say which one is missing, and the
        # names are not secret. The values are never echoed anywhere.
        echo "android-release-signing: ${v} is not set" >&2
        exit 2
    fi
done

if [[ ! -f "${GRADLE}" ]]; then
    echo "android-release-signing: ${GRADLE} not found." >&2
    echo "Run 'pnpm --dir app tauri android init' first - gen/ is generated," >&2
    echo "not tracked. See app/ANDROID.md." >&2
    exit 2
fi
if [[ ! -f "${ANDROID_KEYSTORE_PATH}" ]]; then
    echo "android-release-signing: no keystore at ${ANDROID_KEYSTORE_PATH}" >&2
    exit 2
fi

# Gradle wants an absolute path here; a relative one resolves against whichever
# directory Gradle happens to run in, which is not the one this script is in.
KS_ABS="$(cd "$(dirname "${ANDROID_KEYSTORE_PATH}")" && pwd)/$(basename "${ANDROID_KEYSTORE_PATH}")"

# Mode set before content is written, so the passwords are never briefly
# world-readable on a shared machine.
: > "${GEN}/keystore.properties"
chmod 600 "${GEN}/keystore.properties"
cat > "${GEN}/keystore.properties" <<EOF
storeFile=${KS_ABS}
keyAlias=${ANDROID_KEY_ALIAS}
storePassword=${ANDROID_KEYSTORE_PASSWORD}
password=${ANDROID_KEY_PASSWORD}
EOF
echo "   wrote ${GEN}/keystore.properties (mode 600, contents not printed)"

if grep -q 'keystore.properties' "${GRADLE}"; then
    echo "   build.gradle.kts already reads keystore.properties; left alone"
    exit 0
fi

# Inserted after the opening of the `android {` block, as a self-contained
# addition: a second `buildTypes { }` call reconfigures the existing release
# type rather than replacing it, so nothing the template wrote is edited or
# reordered. Editing inside the template's own blocks would be a patch that
# breaks the next time Tauri changes a line.
TMP="$(mktemp)" || exit 2
awk '
    !done && /^android[[:space:]]*\{/ {
        print
        print "    // Added by scripts/android-release-signing.sh. Reads"
        print "    // keystore.properties, which is written from environment"
        print "    // variables and is never committed - gen/ is not tracked."
        print "    signingConfigs {"
        print "        create(\"release\") {"
        print "            val p = java.util.Properties()"
        print "            val f = rootProject.file(\"keystore.properties\")"
        print "            if (f.exists()) { f.inputStream().use { p.load(it) } }"
        print "            keyAlias = p.getProperty(\"keyAlias\")"
        print "            keyPassword = p.getProperty(\"password\")"
        print "            storeFile = p.getProperty(\"storeFile\")?.let { file(it) }"
        print "            storePassword = p.getProperty(\"storePassword\")"
        print "        }"
        print "    }"
        print "    buildTypes {"
        print "        getByName(\"release\") {"
        print "            signingConfig = signingConfigs.getByName(\"release\")"
        print "        }"
        print "    }"
        done = 1
        next
    }
    { print }
' "${GRADLE}" > "${TMP}" || { rm -f "${TMP}"; exit 2; }

if ! grep -q 'keystore.properties' "${TMP}"; then
    echo "android-release-signing: could not find the 'android {' block in" >&2
    echo "${GRADLE} - the generated template has changed shape. Wire the" >&2
    echo "signing config by hand rather than shipping an unsigned APK." >&2
    rm -f "${TMP}"
    exit 1
fi
mv "${TMP}" "${GRADLE}"
echo "   added a release signingConfig to ${GRADLE}"
