#!/usr/bin/env bash
#
# The hand edits to the generated Android manifest are still there.
#
# `app/src-tauri/gen/` is gitignored — it is generated by `tauri android init`
# and regenerating it is normal. But two lines in the manifest are NOT
# generated: they were added by hand, they are not expressible in
# tauri.conf.json, and nothing in the build notices when they are missing.
#
# Without them the app still compiles, installs and runs. It just cannot use
# the camera: Android denies the permission without ever showing a dialog, so
# QR scanning fails with NotAllowedError and no clue as to why. That cost a
# debugging session once already. A fresh clone regenerates the manifest and
# would land straight back in it, which is what this check exists to prevent.
#
# Run by scripts/check.sh, and a no-op when gen/android has not been generated.

set -uo pipefail
cd "$(dirname "$0")/.."

MANIFEST="app/src-tauri/gen/android/app/src/main/AndroidManifest.xml"

if [[ ! -f "$MANIFEST" ]]; then
    echo "   gen/android not generated here; nothing to check"
    exit 0
fi

missing=()
grep -q 'android.permission.CAMERA' "$MANIFEST" || missing+=("uses-permission android.permission.CAMERA")
grep -q 'android.hardware.camera' "$MANIFEST" || missing+=("uses-feature android.hardware.camera (required=false)")

if (( ${#missing[@]} )); then
    echo "The generated Android manifest is missing hand-added entries:"
    for m in "${missing[@]}"; do echo "  - $m"; done
    echo
    echo "Add them inside <manifest>, above <application>:"
    echo '    <uses-permission android:name="android.permission.CAMERA" />'
    echo '    <uses-feature android:name="android.hardware.camera" android:required="false" />'
    echo
    echo "See app/ANDROID.md. Without them the camera is denied with no dialog."
    exit 1
fi

echo "   camera permission present"
