#!/usr/bin/env bash
#
# The hand edits to the generated Android manifest are still there.
#
# `app/src-tauri/gen/` is gitignored — it is generated by `tauri android init`
# and regenerating it is normal. But two lines in the manifest are NOT
# generated: they were added by hand, they are not expressible in
# tauri.conf.json, and nothing in the build notices when they are missing.
#
# Without them the app still compiles, installs and runs. It just cannot use
# the camera: Android denies the permission without ever showing a dialog, so
# QR scanning fails with NotAllowedError and no clue as to why. That cost a
# debugging session once already. A fresh clone regenerates the manifest and
# would land straight back in it, which is what this check exists to prevent.
#
# Run by scripts/check.sh, and a no-op when gen/android has not been generated.

set -uo pipefail
cd "$(dirname "$0")/.."

MANIFEST="app/src-tauri/gen/android/app/src/main/AndroidManifest.xml"

if [[ ! -f "$MANIFEST" ]]; then
    echo "   gen/android not generated here; nothing to check"
    exit 0
fi

missing=()
grep -q 'android.permission.CAMERA' "$MANIFEST" || missing+=("uses-permission android.permission.CAMERA")
# USB, the second instance of the same lesson. Without the feature Android can
# hand back an empty device list; without the filter file the manifest's
# @xml/device_filter reference dangles and the attach intent cannot fire. Both
# leave BLE working, which is what makes it read as "USB is broken".
grep -q 'android.hardware.usb.host' "$MANIFEST" || missing+=("uses-feature android.hardware.usb.host (run scripts/android-usb-host.sh)")
[[ -f "app/src-tauri/gen/android/app/src/main/res/xml/device_filter.xml" ]] \
    || missing+=("res/xml/device_filter.xml (run scripts/android-usb-host.sh)")
grep -q 'android.hardware.camera' "$MANIFEST" || missing+=("uses-feature android.hardware.camera (required=false)")

if (( ${#missing[@]} )); then
    echo "The generated Android manifest is missing hand-added entries:"
    for m in "${missing[@]}"; do echo "  - $m"; done
    echo
    echo "For the camera, add inside <manifest>, above <application>:"
    echo '    <uses-permission android:name="android.permission.CAMERA" />'
    echo '    <uses-feature android:name="android.hardware.camera" android:required="false" />'
    echo
    echo "For USB, run: ./scripts/android-usb-host.sh"
    echo
    echo "See app/ANDROID.md. Each failure here is silent at runtime: the"
    echo "camera is denied with no dialog, and USB comes back empty while BLE"
    echo "keeps working, which reads as a broken cable rather than a manifest."
    exit 1
fi

echo "   camera and USB host entries present"
