/**
 * EIP-4527 strict schema reader.
 *
 * The invalid cases matter more than the valid ones here. Two decoders that
 * accept the same frames but disagree about which malformed frames to reject
 * have two interpretations of one wire format, and the disagreement surfaces
 * on somebody's device rather than in CI. So every refusal below asserts a
 * specific error CODE, which the firmware corpus will assert too; the
 * human-readable message is allowed to differ between implementations, the
 * code is not.
 */

import { readFileSync } from "node:fs";
import {
  decodeEthSignRequest,
  decodeEthSignature,
  SignDataType,
} from "../src/eip4527/sign-request.ts";
import { E4527, E4527Error } from "../src/eip4527/errors.ts";

let failures = 0;
const check = (cond: boolean, msg: string) => {
  if (!cond) { console.log(`  FAIL: ${msg}`); failures++; }
};
const group = (n: string) => console.log(`== ${n}`);

/* A byte-level builder, so a test can emit things a real encoder would refuse
   to produce - duplicate keys, indefinite lengths, wrong tags. */
const b = (...xs: (number | number[] | Uint8Array)[]): Uint8Array => {
  const out: number[] = [];
  for (const x of xs) {
    if (typeof x === "number") out.push(x);
    else out.push(...x);
  }
  return new Uint8Array(out);
};
const bstr = (n: number) => [0x40 + n];           // byte string, n < 24
const bstr24 = (n: number) => [0x58, n];          // byte string, one-byte len
const zeros = (n: number) => new Uint8Array(n);
const tag = (t: number) =>
  t < 24 ? [0xc0 + t] : t < 256 ? [0xd8, t] : [0xd9, t >> 8, t & 0xff];

/* m/44'/60'/0'/0/0 as a crypto-keypath body: five index/hardened pairs. */
const KEYPATH_BODY = b(
  0xa1, 0x01,                      // map(1), key 1 = components
  0x8a,                            // array(10)
  0x18, 44, 0xf5,
  0x18, 60, 0xf5,
  0x00, 0xf5,
  0x00, 0xf4,
  0x00, 0xf4,
);
const KEYPATH = b(tag(304), KEYPATH_BODY);

const UUID = b(tag(37), bstr(16), zeros(16));

/** A minimal valid request: sign-data, data-type, derivation-path. */
const validRequest = (dataType = 1) => b(
  0xa3,
  0x02, ...[bstr(4)], 0xde, 0xad, 0xbe, 0xef,
  0x03, dataType,
  0x05, KEYPATH,
);

const refuses = (label: string, bytes: Uint8Array, code: E4527, field?: string) => {
  try {
    decodeEthSignRequest(bytes);
    check(false, `${label}: was accepted`);
  } catch (e) {
    if (!(e instanceof E4527Error)) {
      check(false, `${label}: threw ${e}, not an E4527Error`);
      return;
    }
    check(e.code === code, `${label}: got ${e.code}, want ${code}`);
    if (field !== undefined) {
      check(e.field === field, `${label}: field "${e.field}", want "${field}"`);
    }
  }
};

/* The differential gate. Every case the firmware decoded, replayed here, with
 * the requirement that the CODE matches. Equivalent meaning on the valid ones,
 * identical refusal on the invalid ones -- because two decoders that accept the
 * same frames while disagreeing about which malformed ones to reject hold two
 * readings of one format, and that disagreement surfaces on a device rather
 * than in CI.
 *
 * Regenerated by `make -C sim ur-conformance` before this runs; never trusted
 * from git. */
interface FwVector {
  name: string;
  kind: "sign-request" | "signature";
  hex: string;
  expect: string;
  field: string;
}

const fwVectors: FwVector[] = JSON.parse(
  readFileSync(new URL("./eip4527-vectors.json", import.meta.url), "utf8"),
);

group(`firmware differential corpus (${fwVectors.length})`);
{
  const unhexv = (h: string) =>
    new Uint8Array((h.match(/../g) ?? []).map((p) => parseInt(p, 16)));

  for (const fw of fwVectors) {
    const bytes = unhexv(fw.hex);
    let code = "E4527_OK";
    let field = "";
    try {
      if (fw.kind === "signature") decodeEthSignature(bytes);
      else decodeEthSignRequest(bytes);
    } catch (e) {
      if (!(e instanceof E4527Error)) {
        check(false, `${fw.name}: threw ${e}, not an E4527Error`);
        continue;
      }
      code = e.code;
      field = e.field;
    }
    check(code === fw.expect,
      `${fw.name}: TS says ${code}, firmware says ${fw.expect}`);
    if (code !== "E4527_OK" && fw.field !== "") {
      check(field === fw.field,
        `${fw.name}: TS field "${field}", firmware "${fw.field}"`);
    }
  }
}

group("a valid request decodes");
{
  const req = decodeEthSignRequest(validRequest());
  check(req.dataType === SignDataType.Transaction, `dataType ${req.dataType}`);
  check(req.chainId === 1, `chain-id defaulted to ${req.chainId}, want 1`);
  check([...req.signData].join() === "222,173,190,239", "sign-data wrong");
  check(req.derivationPath.components.length === 5,
    `${req.derivationPath.components.length} path components, want 5`);
  check(req.derivationPath.components[0]!.index === 44 &&
        req.derivationPath.components[0]!.hardened === true, "first component wrong");
  check(req.derivationPath.components[4]!.hardened === false, "last component wrong");
  check(req.requestId === undefined, "request-id should be absent");
}

group("all four data types are accepted, and nothing else");
{
  for (const t of [1, 2, 3, 4]) {
    const req = decodeEthSignRequest(validRequest(t));
    check(req.dataType === t, `data-type ${t} decoded as ${req.dataType}`);
  }
  refuses("data-type 0", validRequest(0), E4527.INVALID_DATA_TYPE, "data-type");
  refuses("data-type 5", validRequest(5), E4527.INVALID_DATA_TYPE, "data-type");
  refuses("data-type negative",
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0x20, 0x05, KEYPATH),
    E4527.MALFORMED, "data-type");
  refuses("data-type as text",
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0x61, 0x31, 0x05, KEYPATH),
    E4527.MALFORMED, "data-type");
  refuses("data-type tagged 401",
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, ...tag(401), 0x01, 0x05, KEYPATH),
    E4527.MALFORMED, "data-type");
}

group("duplicate keys are refused, not resolved");
{
  refuses("data-type twice",
    b(0xa4, 0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x03, 0x02, 0x05, KEYPATH),
    E4527.DUPLICATE_FIELD);
}

group("a known tag in the wrong place fails as hard as an unknown one");
{
  refuses("request-id tagged 304",
    b(0xa4, 0x01, ...tag(304), ...bstr(16), zeros(16),
      0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, KEYPATH),
    E4527.WRONG_TAG, "request-id");
  refuses("request-id untagged",
    b(0xa4, 0x01, ...bstr(16), zeros(16),
      0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, KEYPATH),
    E4527.MALFORMED, "request-id");
  refuses("derivation-path tagged 303",
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, ...tag(303), KEYPATH_BODY),
    E4527.WRONG_TAG, "derivation-path");
  refuses("derivation-path untagged",
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, KEYPATH_BODY),
    E4527.MALFORMED, "derivation-path");
  refuses("an unknown tag", 
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, ...tag(9999), KEYPATH_BODY),
    E4527.WRONG_TAG, "derivation-path");
}

group("the top level is not tagged");
{
  refuses("tagged top level", b(...tag(304), validRequest()), E4527.WRONG_TAG);
}

group("fixed-width fields are inflexible");
{
  const withId = (len: number) => b(
    0xa4, 0x01, ...tag(37), ...(len < 24 ? bstr(len) : bstr24(len)), zeros(len),
    0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, KEYPATH);
  refuses("request-id 15 bytes", withId(15), E4527.BAD_LENGTH, "request-id");
  refuses("request-id 17 bytes", withId(17), E4527.BAD_LENGTH, "request-id");

  const withAddr = (len: number) => b(
    0xa4, 0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, KEYPATH,
    0x06, ...bstr24(len), zeros(len));
  refuses("address 19 bytes", withAddr(19), E4527.BAD_LENGTH, "address");
  refuses("address 21 bytes", withAddr(21), E4527.BAD_LENGTH, "address");
}

group("unknown fields and leftovers");
{
  refuses("an undefined key",
    b(0xa4, 0x02, ...bstr(1), 0x00, 0x03, 0x01, 0x05, KEYPATH, 0x09, 0x01),
    E4527.UNKNOWN_FIELD);
  refuses("trailing data", b(validRequest(), 0x00), E4527.TRAILING_DATA);
  refuses("a missing sign-data",
    b(0xa2, 0x03, 0x01, 0x05, KEYPATH), E4527.MISSING_FIELD, "sign-data");
}

group("constructs outside the grammar");
{
  refuses("an indefinite-length map",
    b(0xbf, 0x03, 0x01, 0xff), E4527.MALFORMED);
  refuses("an indefinite-length byte string",
    b(0xa3, 0x02, 0x5f, 0x41, 0x00, 0xff, 0x03, 0x01, 0x05, KEYPATH),
    E4527.MALFORMED, "sign-data");
  refuses("a float",
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0xf9, 0x3c, 0x00, 0x05, KEYPATH),
    E4527.MALFORMED, "data-type");
  refuses("null", 
    b(0xa3, 0x02, ...bstr(1), 0x00, 0x03, 0xf6, 0x05, KEYPATH),
    E4527.MALFORMED, "data-type");
}

group("eth-signature is 65 bytes, exactly");
{
  const sig = (len: number) => b(
    0xa2, 0x01, UUID, 0x02, ...bstr24(len), zeros(len));
  const ok = decodeEthSignature(sig(65));
  check(ok.signature.length === 65, `signature ${ok.signature.length} bytes`);
  check(ok.requestId.length === 16, "request-id wrong length");

  for (const len of [64, 66]) {
    try {
      decodeEthSignature(sig(len));
      check(false, `a ${len}-byte signature was accepted`);
    } catch (e) {
      check(e instanceof E4527Error && e.code === E4527.BAD_LENGTH,
        `a ${len}-byte signature gave ${e}`);
    }
  }
}

console.log(`\n${failures ? "FAILED" : "PASSED"} (${failures} failure${failures === 1 ? "" : "s"})`);
process.exit(failures ? 1 : 0);
