/**
 * Fountain fragment selection, against vectors the FIRMWARE produced.
 *
 * This is the mirror that matters most. The subset a mixed part carries is
 * never transmitted — both ends derive it — so an implementation that derives
 * it differently produces no error, just a message that fails its checksum,
 * indistinguishable from a camera misread. And the derivation runs through
 * doubles, so passing this suite is also an assertion that C and JavaScript
 * agree bit for bit about IEEE-754 arithmetic.
 *
 * Regenerated by `make -C sim ur-conformance` before this runs; never trusted
 * from git.
 */

import { readFileSync } from "node:fs";
import { sha256 } from "@noble/hashes/sha256";
import { chooseFragments, Xoshiro256, UR_MAX_PARTS } from "../src/ur-fountain.ts";

let failures = 0;
const check = (cond: boolean, msg: string) => {
  if (!cond) { console.log(`  FAIL: ${msg}`); failures++; }
};
const group = (n: string) => console.log(`== ${n}`);

interface Vector {
  seqNum: number;
  seqLen: number;
  checksum: number;
  fragments: number[];
}

const vectors: Vector[] = JSON.parse(
  readFileSync(new URL("./ur-fountain-vectors.json", import.meta.url), "utf8"),
);

const mixed = vectors.filter((v) => v.seqNum > v.seqLen);

group(`firmware vectors (${vectors.length}, ${mixed.length} mixed-degree)`);
check(vectors.length > 0, "no vectors were loaded");
check(mixed.length > 500, `only ${mixed.length} mixed-degree vectors; the pure path proves little`);

let mismatches = 0;
for (const v of vectors) {
  const got = chooseFragments(v.seqNum, v.seqLen, v.checksum);
  const same =
    got.length === v.fragments.length &&
    got.every((x, i) => x === v.fragments[i]);
  if (!same) {
    if (mismatches < 3) {
      console.log(
        `  FAIL: part ${v.seqNum}/${v.seqLen} crc ${v.checksum}\n` +
        `         ts: [${got}]\n         fw: [${v.fragments}]`,
      );
    }
    mismatches++;
  }
}
check(mismatches === 0, `${mismatches} of ${vectors.length} vectors disagree with the firmware`);

group("parts 1..seqLen are the plain fragments");
for (let seqLen = 1; seqLen <= 24; seqLen++) {
  for (let n = 1; n <= seqLen; n++) {
    const f = chooseFragments(n, seqLen, 0xdeadbeef);
    check(f.length === 1 && f[0] === n - 1,
      `part ${n} of ${seqLen} gave [${f}], want [${n - 1}]`);
  }
}

group("mixed parts have a usable degree");
for (let seqLen = 1; seqLen <= 32; seqLen++) {
  for (let n = seqLen + 1; n <= seqLen + 20; n++) {
    const d = chooseFragments(n, seqLen, 0x01020304).length;
    check(d >= 1 && d <= seqLen, `part ${n} of ${seqLen} has degree ${d}`);
  }
}

group("out-of-range inputs are refused");
{
  const rejects = (label: string, fn: () => unknown) => {
    let threw = false;
    try { fn(); } catch { threw = true; }
    check(threw, `${label} was accepted`);
  };
  rejects("a zero fragment count", () => chooseFragments(1, 0, 0));
  rejects("part zero", () => chooseFragments(0, 4, 0));
  rejects("a count above UR_MAX_PARTS", () => chooseFragments(1, UR_MAX_PARTS + 1, 0));
  check(chooseFragments(1, UR_MAX_PARTS, 0).length === 1, "exactly UR_MAX_PARTS was refused");
}

/* The generator is 64-bit; JavaScript numbers are not. If BigInt handling were
 * wrong the vectors above would already fail, but a direct check localises the
 * fault to the RNG rather than the alias table. */
group("the generator is 64-bit clean");
{
  /* Seeded from a real digest, not from a constant fill. All four state words
     equal makes xoshiro degenerate: s2 and s3 cancel to zero on the first step
     and s1 is unchanged, so the second output repeats the first. That is a
     property of the seed, not a fault, and the real code always seeds from
     SHA-256 -- but a constant fill here made this check fail against a mirror
     that agrees with the firmware on all 1835 vectors, which is exactly the
     kind of test that gets a correct implementation "fixed". */
  const rng = new Xoshiro256(sha256(new TextEncoder().encode("leek")));
  const seen = new Set<string>();
  let maxBits = 0;
  for (let i = 0; i < 64; i++) {
    const v = rng.next();
    seen.add(v.toString());
    maxBits = Math.max(maxBits, v.toString(2).length);
    check(v >= 0n && v < (1n << 64n), `output ${v} is outside uint64`);
  }
  check(seen.size === 64, "the generator repeated a value within 64 draws");
  check(maxBits > 60, `widest output was ${maxBits} bits; the top of the word looks unused`);
}

console.log(`\n${failures ? "FAILED" : "PASSED"} (${failures} failure${failures === 1 ? "" : "s"})`);
process.exit(failures ? 1 : 0);
