/**
 * BC-UR codec tests, replaying vectors the FIRMWARE produced.
 *
 * This file is the redemption of a promise `sim/test_ur.c` has been making
 * since the C side was written: "Shared with app/packages/core/test/ur.test.ts,
 * for the same reason the CBOR vectors are: two implementations of one wire
 * format drift unless something forces them to agree."
 *
 * `ur-vectors.json` is regenerated by `make -C sim ur-conformance` before this
 * runs (see scripts/check.sh), never trusted from git. A corpus recorded from
 * an older `src/ur.c` would let this mirror agree with an encoder nobody runs
 * — the exact failure docs/MIRROR-GAP.md was written about, where the mock was
 * twice more permissive than protocol.c and passed a green suite.
 */

import { readFileSync } from "node:fs";
import {
  crc32,
  bytewordsEncode,
  bytewordsDecode,
  urEncode,
  urDecode,
  isMultipart,
} from "../src/ur.ts";

let failures = 0;
const check = (cond: boolean, msg: string) => {
  if (!cond) { console.log(`  FAIL: ${msg}`); failures++; }
};
const group = (n: string) => console.log(`== ${n}`);

const hex = (b: Uint8Array) => [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
const unhex = (s: string) =>
  new Uint8Array((s.match(/../g) ?? []).map((p) => parseInt(p, 16)));

interface Vector {
  length: number;
  payloadHex: string;
  crc32: number;
  bytewords: string;
  ur: string;
}

const vectors: Vector[] = JSON.parse(
  readFileSync(new URL("./ur-vectors.json", import.meta.url), "utf8"),
);

group(`firmware vectors (${vectors.length})`);
check(vectors.length > 0, "no vectors were loaded");

for (const v of vectors) {
  const payload = unhex(v.payloadHex);
  check(payload.length === v.length, `${v.length}: vector is self-inconsistent`);

  check(crc32(payload) === v.crc32,
    `${v.length}: crc32 ${crc32(payload)} != firmware ${v.crc32}`);

  const encoded = bytewordsEncode(payload);
  check(encoded === v.bytewords,
    `${v.length}: bytewords differ\n         ts: ${encoded}\n         fw: ${v.bytewords}`);

  const decoded = bytewordsDecode(v.bytewords);
  check(hex(decoded) === v.payloadHex,
    `${v.length}: decoding the firmware's bytewords gave ${hex(decoded)}`);

  const ur = urEncode("eth-signature", payload);
  check(ur === v.ur,
    `${v.length}: UR differs\n         ts: ${ur}\n         fw: ${v.ur}`);

  const back = urDecode(v.ur);
  check(back.type === "eth-signature", `${v.length}: type came back "${back.type}"`);
  check(hex(back.payload) === v.payloadHex, `${v.length}: UR payload changed`);
}

/* A misread frame must be refused rather than decoded into something
 * plausible. That is the entire reason the checksum is on the wire, and a
 * checksum that is present but unchecked looks identical to one that works
 * until a camera misreads a frame. */
group("a corrupted frame is refused");
{
  const payload = new Uint8Array([0xde, 0xad, 0xbe, 0xef, 0x00, 0x11, 0x22]);
  const good = bytewordsEncode(payload);
  let accepted = 0;
  for (let i = 0; i < good.length; i++) {
    const broken =
      good.slice(0, i) + (good[i] === "a" ? "z" : "a") + good.slice(i + 1);
    try {
      bytewordsDecode(broken);
      accepted++;
    } catch { /* expected */ }
  }
  check(accepted === 0, `${accepted} single-character corruptions were accepted`);
}

group("malformed input");
{
  const rejects = (label: string, fn: () => unknown) => {
    let threw = false;
    try { fn(); } catch { threw = true; }
    check(threw, `${label} was accepted`);
  };
  rejects("an odd-length string", () => bytewordsDecode("aeadao1"));
  rejects("a string too short for a checksum", () => bytewordsDecode("aeadao"));
  rejects("a pair matching no byteword", () => bytewordsDecode("qqqqqqqq"));
  rejects("a UR with no scheme", () => urDecode("eth-signature/aeaeaeae"));
  rejects("a type containing a space", () => urDecode("ur:eth signature/aeaeaeae"));
  rejects("a type starting with a hyphen", () => urEncode("-bad", new Uint8Array()));
  rejects("a multi-part UR", () => urDecode("ur:bytes/1-3/aeaeaeae"));
}

/* Readers uppercase the whole string to reach the QR alphanumeric mode, which
 * is a smaller code on a small screen. An uppercase UR has to mean the same
 * thing. */
group("case insensitivity");
{
  const ur = urEncode("eth-sign-request", new Uint8Array([1, 2, 3]));
  const upper = urDecode(ur.toUpperCase());
  check(upper.type === "eth-sign-request", `type came back "${upper.type}"`);
  check(hex(upper.payload) === "010203", "payload changed when uppercased");
}

group("multi-part detection");
{
  check(isMultipart("ur:eth-sign-request/1-3/aeaeaeae"), "multi-part not detected");
  check(!isMultipart("ur:eth-signature/aeaeaeae"), "single-part called multi-part");
}

console.log(`\n${failures ? "FAILED" : "PASSED"} (${failures} failure${failures === 1 ? "" : "s"})`);
process.exit(failures ? 1 : 0);
