/**
 * Build the unpacked extension into `dist/`.
 *
 * Three Vite passes, in this order, because they are not interchangeable:
 *
 *   1. The module pass — popup.html, offscreen.html and the service worker.
 *      These are extension PAGES (and an MV3 worker declared `"type":
 *      "module"`), so they get real ES modules and share chunks. viem and
 *      @noble are the bulk of the bytes and both the popup and the offscreen
 *      document reach `packages/core`, so sharing is worth something.
 *
 *   2, 3. One single-file IIFE pass per content script. Chrome injects
 *      `content_scripts` as classic scripts: an `import` statement in
 *      `content.js` or `inpage.js` is a syntax error at injection time, and
 *      the failure is silent — the page loads, the provider is simply never
 *      announced. That is the worst thing a wallet can do, so the two content
 *      scripts are built separately and each is forced into a single file.
 *
 * Then the manifest and the icons are copied. They are copied rather than
 * imported so that `manifest.json` in the repository is the literal bytes
 * Chrome loads: a manifest generated by a build step is a manifest nobody
 * reviews, and it is the file that declares this extension's permissions.
 *
 * `emptyOutDir` is true only on the first pass, or passes 2 and 3 would delete
 * what pass 1 just wrote.
 */

import { build } from "vite";
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "dist");

/** Pass 1: the pages and the worker. */
async function buildModules() {
  await build({
    configFile: join(here, "vite.config.ts"),
    build: {
      emptyOutDir: true,
      rollupOptions: {
        input: {
          popup: join(here, "popup.html"),
          offscreen: join(here, "offscreen.html"),
          background: join(here, "src/background.ts"),
        },
        output: {
          format: "es",
          /* The manifest names `background.js` at the root of the package, so
           * entry files may not be hashed or nested. Chunks and assets may be,
           * and are, because nothing references them by a fixed name. */
          entryFileNames: "[name].js",
          chunkFileNames: "chunks/[name]-[hash].js",
          assetFileNames: "assets/[name]-[hash][extname]",
        },
      },
    },
  });
}

/** Passes 2 and 3: one self-contained classic script each. */
async function buildContentScript(name) {
  await build({
    configFile: join(here, "vite.config.ts"),
    build: {
      emptyOutDir: false,
      lib: {
        entry: join(here, `src/${name}.ts`),
        formats: ["iife"],
        /* IIFE needs a global name even when nothing reads it. This one is
         * never referenced: the script's whole effect is its side effects. */
        name: `leekwallet_${name}`,
        fileName: () => `${name}.js`,
      },
      /* Rollup's code splitting is off in library mode, which is what
       * guarantees the single file the manifest names. Nothing more is needed
       * here - an earlier version set `inlineDynamicImports`, which Vite warns
       * is ignored for exactly that reason. */
      rollupOptions: {
        output: { assetFileNames: "assets/[name]-[hash][extname]" },
      },
    },
  });
}

/**
 * Copy the static files, and check the manifest still describes what was
 * built.
 *
 * The check is cheap and it catches the class of mistake that is otherwise
 * only found by loading the extension and watching nothing happen: a renamed
 * entry point, a content script that quietly stopped being emitted.
 */
async function copyStatic() {
  await cp(join(here, "manifest.json"), join(dist, "manifest.json"));
  await mkdir(join(dist, "icons"), { recursive: true });
  await cp(join(here, "icons"), join(dist, "icons"), { recursive: true });

  const manifest = JSON.parse(await readFile(join(dist, "manifest.json"), "utf8"));
  const required = [
    manifest.background.service_worker,
    ...manifest.content_scripts.flatMap((c) => c.js),
    manifest.action.default_popup,
    "offscreen.html",
  ];
  const missing = [];
  for (const file of required) {
    await readFile(join(dist, file)).catch(() => missing.push(file));
  }
  if (missing.length > 0) {
    throw new Error(
      `the manifest names files the build did not produce: ${missing.join(", ")}`,
    );
  }
  return manifest;
}

/**
 * Vite writes `<script type="module" src="./src/popup.ts">` out as a hashed
 * asset path, which is correct — but the HTML it emits sits at `dist/popup.html`
 * and refers to `/popup.js` with a leading slash, an absolute path that in an
 * extension resolves against the extension root. That happens to be right
 * here, and this function asserts it rather than assuming it, because a
 * leading-slash path that started resolving somewhere else would produce a
 * popup that renders an empty shell with no error anywhere.
 */
async function checkHtml() {
  for (const page of ["popup.html", "offscreen.html"]) {
    const html = await readFile(join(dist, page), "utf8");
    const fixed = html.replace(/(src|href)="\/(?!\/)/g, '$1="./');
    if (fixed !== html) await writeFile(join(dist, page), fixed);
    if (!/<script[^>]+src=/.test(fixed)) {
      throw new Error(`${page} came out of the build with no script tag`);
    }
  }
}

const manifest = await (async () => {
  await buildModules();
  await buildContentScript("content");
  await buildContentScript("inpage");
  await checkHtml();
  return await copyStatic();
})();

console.log(
  `\nLeekWallet ${manifest.version} built into extension/dist — ` +
  "load it with chrome://extensions -> Developer mode -> Load unpacked.",
);
